[package]
name = "rust-beats"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
hound = "3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
mp3lame-encoder = "0.2"